### ISSUE TITLE
Branch Cleanup

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#105]
It's time to remove lots of old / stale branches.   

Visit: https://github.com/JCSDA/CRTMv3/branches

**Comment by chengdang** [comment]
Removed branches that have been merged into development.

The following branches are under development:
```
feature/cd_TOA_R
hotfix/cd_CodeFormat
feature/cd_WRFAOD
```
The following branch has just been merged this week; keeping it for a while to make sure all codes are running properly:
`feature/cd_RTSout_netCDF`
