### ISSUE TITLE
GOCART-GEOS5 LUT with BRC

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#112]
In [issue](https://github.com/JCSDA-internal/crtm/issues/402), based on the GOCART Optics used in geos_aero AOD operator (https://github.com/JCSDA-internal/geos-aero/tree/develop/test/Data), I concluded that the phase function coefficient of the following tables are not available:
optics_DU.v15_3.nc
optics_SS.v3_3.nc
optics_OC.v1_3.nc
optics_BRC.v1_5.nc
optics_BC.v1_3.nc
optics_SU.v1_3.nc
optics_NI.v2_5.nc

I'd like to update that the `pmom` variables are available in a different set of the same tables, via personal connection. This allow us to reconstruct the phase functions, and enable us to implement them in CRTM. 
I'll make this table ready before the code sprint next week. @mer-a-o @jeromebarre. This will help clarify the aerosol mapping scheme in [issue](https://github.com/JCSDA-internal/fv3-jedi/issues/1142)

**Comment by chengdang** [comment]
The difference between the two sets of GOCART tables are still valid, as mentioned in issue https://github.com/JCSDA-internal/crtm/issues/402

Based on email correspondence, as of Aug 2022, the tables used in GOCART are:
optics_DU.v15_3.nc
optics_SS.v3_3.nc
optics_OC.v1_3.nc
optics_BRC.v1_5.nc
optics_BC.v1_3.nc
optics_SU.v1_3.nc
optics_NI.v2_5.nc

The CRTM GOCART-GEOS5 LUT generated in 2021, were based on the following LUTs:
optics_BC.v1_6.nc
optics_DU.v15_6.nc
optics_NI.v2_6.nc
optics_OC.v1_6.nc
optics_SS.v3_6.nc
optics_SU.v1_6.nc

**Comment by chengdang** [comment]
New GOCART-GEOS5 table with brown carbon is created with an updated version number.`VERSION = 2, RELEASE = 4`

The `pcoeffs` in this new table are currently set as 0 because the delta fit package cannot be imported on M1 machine (issue with package f2py, still under investigation).

This new table is however sufficient for AOD calculation; ready for the AOD code sprint next week.

**Comment by chengdang** [comment]
The updated table with pcoeff is ready for testing, with the following aerosols included:
```
 Aerosol_Type_Name =
  "DU1",
  "DU2",
  "DU3",
  "DU4",
  "DU5",
  "SS1",
  "SS2",
  "SS3",
  "SS4",
  "SS5",
  "OC1",
  "OC2",
  "BC1",
  "BC2",
  "SU1",
  "SU2",
  "NI1",
  "NI2",
  "NI3",
  "BRC1",
  "BRC2" ;
}
```

**Comment by chengdang** [comment]
Here are the global attributes of the new table for future reference:

```
// global attributes:
		:Release = 4 ;
		:Version = 2 ;
		:Data_Source = "GOCART-GEOS5" ;
		:Title = "Aerosol Optical Properties in the infrared and visible spectral region" ;
		:History = "Combine GOCART LUTs (Cheng DAND, 2024)" ;
		:Comment = "Based on GOCART LUTs: optics_DU.v15_5.nc, optics_SS.v3_5.nc, optics_BC.v1_5.nc, optics_OC.v1_5.nc, optics_SU.v2_5.nc, optics_NI.v2_5, optics_BRC.v2_5.nc, with delta fit applied to phase function" ;
```

**Comment by jeromebarre** [comment]
Thanks! I might try to add this in v8 but not sure i'll have time...

**Comment by chengdang** [comment]
@jeromebarre thanks Jerome! I guess the structures are almost ready in UFO. This table will be named as GOCART-GEOS5 too as a replacement of the current table. Once the BRC is ready in geoval and this table is added to CRTM fix folder, we should be able to uncomment the BRC mapping to use this table. But yes, there will be more time consuming testings, for which please let me know if there is anything I can help with.
