### ISSUE TITLE
explore fractional cloud selection on fractional aerosol impact 

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#127]
In #117, we found that the choice of cloud fraction has an impact on the aerosol-modified radiances as well.  This isn't desirable behavior.  The purpose of this issue is to verify that the aerosol radiances are still influenced, even for very low cloud content (i.e., where clouds would not dominate the radiances), and to verify that this impacts visible and infrared radiances. 

Test 1:  tiny cloud water content values for various/tiny cloud fractions, looking at whether aerosol-dominated radiances are influenced by the choice of cloud fraction. 

Feel free to provide results of additional tests here.

**Comment by chengdang** [comment]
Updates: 
Currently, it seems there are no existing geovals contain both cloud and aerosol information in JEDI.
The test will for now adopt the simplified sample profiles in CRTM unit tests.

**Comment by BenjaminTJohnson** [comment]
@chengdang this is strange, right?  There's almost always aerosols and clouds together in reality.   

@gthompsnJCSDA @jeromebarre  Greg/Jerome,  would like to get your quick input on the observation that Cheng has made that there's no geovals that contain both clouds and aerosols - any thoughts?

**Comment by jeromebarre** [comment]
What are the geovals, where do they come from?

**Comment by chengdang** [comment]
**NOTE: it is important to note that the cloud content of these tests are constant, which is a wrong approach to set up this test. 
Keeping these figures for future references only, the results do not represent the test results of this issue.**


Tests for two sample profiles (top/bottom), color/numbers are cloud cover fraction:

Brightness temperature
![cris399_npp_BT](https://github.com/JCSDA/CRTMv3/assets/18148322/be6f2ae0-2fae-466c-b371-316a9fe30e5e)

Radiance
![cris399_npp_Radiance](https://github.com/JCSDA/CRTMv3/assets/18148322/75c21105-4542-44f0-b1f9-d3167e736a09)

**Comment by chengdang** [comment]
Radiance
![cris399_npp_Radiance](https://github.com/JCSDA/CRTMv3/assets/18148322/75c21105-4542-44f0-b1f9-d3167e736a09)

**Comment by chengdang** [comment]
> What are the geovals, where do they come from?

It's the modeled state variables right? @jeromebarre

**Comment by jeromebarre** [comment]
I meant where as skylab or input data of ctest or else? What instrument product footprint? etc etc

**Comment by BenjaminTJohnson** [comment]
Just to close this issue (for now):  It appears that cloud fraction doesn't actually impact the aerosol-impacted radiance calculations.  We ran several tests at different cloud fractions using small cloud contents (neglible vs. clear sky) for IR channels, and there was no notable difference in the aerosol-impacted radiances. 

This is also  evident from the source code, in 
```
               ! Copy the clear-sky AtmOptics
               IF ( CRTM_Atmosphere_IsFractional(cloud_coverage_flag) ) THEN
                  Error_Status = CRTM_AtmOptics_NoScatterCopy( AtmOptics(nt), AtmOptics_Clear(nt) )
               END IF

               ! Compute the cloud particle absorption/scattering properties
               IF( Atm%n_Clouds > 0 ) THEN
                  Error_Status = CRTM_Compute_CloudScatter( Atm         , &  ! Input
                       GeometryInfo, &  ! Input
                       SensorIndex , &  ! Input
                       ChannelIndex, &  ! Input
                       AtmOptics(nt)   , &  ! Output
                       CSvar(nt)         )  ! Internal variable output
               END IF

               ! Compute the aerosol absorption/scattering properties
               IF ( Atm%n_Aerosols > 0 ) THEN
                  Error_Status = CRTM_Compute_AerosolScatter( Atm         , &  ! Input
                       SensorIndex , &  ! Input
                       ChannelIndex, &  ! Input
                       AtmOptics(nt)   , &  ! In/Output
                       ASvar(nt)         )  ! Internal variable output
               END IF
<..>
               CALL CRTM_Compute_Transmittance(AtmOptics(nt),transmittance)
               SfcOptics(nt)%Transmittance = transmittance
               ! ...Clear sky for fractional cloud cover
               IF ( CRTM_Atmosphere_IsFractional(cloud_coverage_flag) ) THEN
                  CALL CRTM_Compute_Transmittance(AtmOptics_Clear(nt),transmittance_clear)
                  SfcOptics_Clear(nt)%Transmittance = transmittance_clear
               END IF
<...>
                  Error_Status = CRTM_Compute_RTSolution( &
                       Atm             , &  ! Input
                       Surface(m)      , &  ! Input
                       AtmOptics(nt)       , &  ! Input
                       SfcOptics(nt)      , &  ! Input
                       GeometryInfo    , &  ! Input
                       SensorIndex     , &  ! Input
                       ChannelIndex    , &  ! Input
                       RTSolution(ln,m), &  ! Output
                       RTV(nt)               )  ! Internal variable output
 <...>
<...>
               IF ( CRTM_Atmosphere_IsFractional(cloud_coverage_flag) ) THEN
                  DO ks = 1, RTV(nt)%n_Stokes
                     RTSolution(ln,m)%Stokes(ks) = &
                          ((ONE - CloudCover%Total_Cloud_Cover) * RTSolution_Clear(nt)%Stokes(ks)) + &
                          (CloudCover%Total_Cloud_Cover * RTSolution(ln,m)%Stokes(ks))
                     ! ...Save the cloud cover in the output structure
                     RTSolution(ln,m)%Total_Cloud_Cover = CloudCover%Total_Cloud_Cover
                  END DO
                  RTSolution(ln,m)%Radiance = RTSolution(ln,m)%Stokes(1)
 
```

The code says that the all-sky transmittance is copied

**Comment by BenjaminTJohnson** [comment]
closing this issue.  After rigorous testing, compensating for the change in cloud water content with changes in cloud_fraction, I find that there's no cloud fraction influence on the aerosol-impacted radiances.
