### ISSUE TITLE
Issue with surface reflectivity

### ISSUE THREAD

**Issue by imoradi** [JCSDA/CRTMv3#128]
There seems to be a bug with surface emissivity calculations so that the calculated reflectivity is outside the range for MW instruments. I am using FASTEM V6.0.

 CRTM_Compute_RTSolution(WARNING) : Error assigning input for RTSolution algorithms
 CRTM_Forward(WARNING) : Error computing RTSolution for atms_npp, channel 2, profile #856
 Assign_Common_Input(WARNING) : WARNING SfcOptics%Reflectivity out of bounds [0,1]:   0.0000      1.0069
 Assign_Common_Input(WARNING) : WARNING SfcOptics%Reflectivity out of bounds [0,1]:   0.0000      1.0388
.
.
 CRTM_Forward(WARNING) : Error computing RTSolution for atms_npp, channel 16, profile #365
 Assign_Common_Input(WARNING) : WARNING SfcOptics%Reflectivity out of bounds [0,1]:   0.0000      1.0578
 CRTM_Compute_RTSolution(WARNING) : Error assigning input for RTSolution algorithms

The weird thing is that this only happens when doing all-sky whether with the default CloudCoeff or the DDA one - it does not matter.

I have a slightly older version of CRTM V3.0 that was cloned couple of months ago and that works fine so this bug was likely introduced recently.

**Comment by BenjaminTJohnson** [comment]
you need to update with the latest version of develop, I merged a PR into
develop that exposed this issue, and reverted it because it was breaking
things right before the skylabv8 release.  I'll work on this in the
background.

**Comment by imoradi** [comment]
OK, thank you.

**Comment by chengdang** [comment]
Finished
