### ISSUE TITLE
Reff in AerosolCoeff.CMAQ tables

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#130]
In CAMQ aerosols coefficient tables, there are a total 35 effective radii for each species, and the radii of all 8 species are indentical:
```
 Reff =
  0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
    0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.25, 2.5, 2.75,
    3, 3.5, 4, 4.5, 5, 6, 7.5,
  0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
    0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.25, 2.5, 2.75,
    3, 3.5, 4, 4.5, 5, 6, 7.5,
  0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
    0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.25, 2.5, 2.75,
    3, 3.5, 4, 4.5, 5, 6, 7.5,
  0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
    0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.25, 2.5, 2.75,
    3, 3.5, 4, 4.5, 5, 6, 7.5,
  0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
    0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.25, 2.5, 2.75,
    3, 3.5, 4, 4.5, 5, 6, 7.5,
  0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
    0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.25, 2.5, 2.75,
    3, 3.5, 4, 4.5, 5, 6, 7.5,
  0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
    0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.25, 2.5, 2.75,
    3, 3.5, 4, 4.5, 5, 6, 7.5,
  0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
    0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.25, 2.5, 2.75,
    3, 3.5, 4, 4.5, 5, 6, 7.5 ;
```

This implies that these are not RH-scaled Reff (i.e. the hydrophilic growth factors should be different for different species). Therefore, Reff/RH in CMAQ table cannot be used as the Reff/RH in CRTM default tables for interpolating effective radius, as in function `gocart_aerosol_size`
https://github.com/JCSDA-internal/ufo/blob/7ebbdc3f5e3de367b9a7f60a13f9bc43b13161a3/src/ufo/operators/crtm/ufo_crtm_utils_mod.F90#L1708. This is causing an issue in JEDI (noticed by @PatNichols) in recent V8 release, with the new CMAQ capability 

**Question to the CMAQ table deliveree** : 
Yingtao @YingtaoMa, how did you adjust the effective radius when adopting the CMAQ table? What are the assumed hydrophilic growth factors of different species? Thanks.

**Possible fix to the V8 release**:
- Replace `gocart_aerosol_size` with a new function to compute Reff based on atm%RH, in the CMAQ option: https://github.com/JCSDA-internal/ufo/blob/7ebbdc3f5e3de367b9a7f60a13f9bc43b13161a3/src/ufo/operators/crtm/ufo_crtm_utils_mod.F90#L1577
- Relative humidity will be a required input with CMAQ option https://github.com/JCSDA-internal/ufo/blob/7ebbdc3f5e3de367b9a7f60a13f9bc43b13161a3/src/ufo/operators/crtm/ufo_crtm_utils_mod.F90#L713 
- CMAQ option should be disabled until this is fixed.

Any suggestions or insights are welcome! @jeromebarre @YingtaoMa @BenjaminTJohnson. Thank you!

**Comment by chengdang** [comment]
This is a drafted branch with proposed fix:
https://github.com/JCSDA-internal/ufo/tree/feature/cmaq_reff

Unfortunately, a lot of hard-coded parameters are required in function [cmaq_aerosol_size](https://github.com/JCSDA-internal/ufo/blob/127361b042bcb8df30f431e5a8884ca9397a7dd6/src/ufo/operators/crtm/ufo_crtm_utils_mod.F90#L1752), based on over-simplified assumptions:
```
     ! Reff_Dry and Growth_Factor are approximated based on GOCART-GEOS5 tables (species DU3 etc)
     ! Dust          - 1 -> DU3
     ! Soot          - 2 -> BC2
     ! Water soluble - 3 -> OC2
     ! Sulfate       - 4 -> Sulfate 2
     ! Sea salt      - 5 -> Sea Salt 3
     ! Water         - 6 -> OC2
     ! Insoluble     - 7 -> DU3
     ! dust-like     - 8 -> DU3
```

I have not complied the code, so it is not ready for testing (especially the parameter definition part) but just to show the concept for now. Any suggestions are welcome.

**Comment by jeromebarre** [comment]
Can you create a draft PR so I can start putting code-specific comments? 
Do you think we should replace the default `gocart_aerosol_size`  by `cmaq_aerosol_size`? I don't think we should replace the default but have a condition that checks on which aerosol model. I can point to and comment on the lines I am talking about in a draft PR. Thanks!

**Comment by chengdang** [comment]
Yes! I just created a PR: https://github.com/JCSDA-internal/ufo/pull/3283

And I agree with you we should not replace the default gocart_aerosol_size.
For now, I'm only using cmaq_aerosol_size for CMAQ options.

**Comment by chengdang** [comment]
Noticed this bug has been temporarily removed by setting n_RH = 35 in function gocart_aerosol_size, which will introduce a bit bias for CRTM calculations with the default table, for very high relative humidity RH > 0.98
