### ISSUE TITLE
Add relative humidity to CRTM_Atmosphere_AddLayers (_TL, _AD)

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#133]
`atm%Relative_Humidity` needs to be added to functions` CRTM_Atmosphere_AddLayers*`.

**Comment by chengdang** [comment]
For RH to be properly implemented in CRTM_Atmosphere_AddLayers (_TL, _AD), it seems the climatologies of level_RH are needed, in a similar set up for temperature (TROPICAL, MIDLATITUDE_SUMMER, MIDLATITUDE_WINTER, SUBARCTIC_SUMMER, SUBARCTIC_WINTER, US_STANDARD_ATMOSPHERE)

In `MODULE CRTM_Model_Profiles`
```
  ! ----------------------
  ! Module data statements
  ! ----------------------
  REAL(fp), SAVE :: Level_Temperature(0:N_MODEL_LAYERS,N_MODELS)
  DATA Level_Temperature(:,TROPICAL) / &
    178.174_fp,  192.328_fp,  210.111_fp,  225.459_fp,  239.120_fp, &
    251.516_fp,  258.971_fp,  264.536_fp,  268.260_fp,  269.940_fp, &
    267.898_fp,  263.813_fp,  259.762_fp,  256.009_fp,  252.506_fp, &
    249.223_fp,  246.228_fp,  243.425_fp,  240.822_fp,  238.354_fp, &
    236.044_fp,  233.852_fp,  231.779_fp,  229.858_fp,  228.013_fp, &
    226.216_fp,  224.456_fp,  222.760_fp,  221.135_fp,  219.623_fp, &
    218.157_fp,  216.716_fp,  215.232_fp,  213.323_fp,  211.116_fp, &
    208.960_fp,  206.863_fp,  204.840_fp,  202.874_fp,  201.054_fp, &
    199.289_fp,  197.557_fp,  195.862_fp,  195.130_fp,  196.031_fp, &
    196.910_fp,  199.292_fp,  201.792_fp,  204.249_fp,  206.692_fp, &
    209.083_fp,  211.535_fp,  214.055_fp,  216.524_fp,  218.876_fp, &
    221.164_fp,  223.408_fp,  225.700_fp,  227.958_fp,  230.178_fp, &
    232.509_fp,  234.797_fp,  237.043_fp,  239.252_fp,  241.422_fp, &
    243.553_fp,  245.698_fp,  247.807_fp,  249.880_fp,  251.983_fp, &
    254.067_fp,  256.118_fp,  258.148_fp,  260.155_fp,  262.131_fp, &
    264.092_fp,  266.071_fp,  268.020_fp,  269.939_fp,  271.870_fp, &
    273.782_fp,  275.665_fp,  277.531_fp,  279.397_fp,  281.235_fp, &
    283.047_fp,  284.395_fp,  285.475_fp,  286.540_fp,  287.590_fp, &
    289.118_fp,  290.683_fp,  292.227_fp,  293.750_fp,  295.281_fp, &
    296.790_fp,  298.280_fp,  299.749_fp,  301.199_fp,  302.630_fp, &
    304.043_fp /
...
```

**Comment by chengdang** [comment]
On a side note, it seems the `Climatology` is always set as `US_STANDARD_ATMOSPHERE` in UFO, meanwhile the different climatologies are used for Tau coef. generation in CRTM. Will such discrepancy have any impact on the DA?

**Comment by BenjaminTJohnson** [comment]
It shouldn't have any impact if all of the correct variables are specified replacing the background climatology.

Probably worth a test ?

**Comment by chengdang** [comment]
Follow up on this issue:

In CRTM, RH is only used for the calculation of aerosol optical properties, hence there is no need to extend the RH layers as how CRTM extends pressure and temperature. 

With function `CRTM_Atmosphere_AddLayers*`, the extended pressure layers are appended to the end of user-input pressure layers. Though CRTM does not extend the input aerosol/cloud properties, the pressure/layer indices of user-input profiles are still correct when computing AtmOptics. 


This is a aerosol-only test with 15 aerosol layers at the bottom. The extended pressure levels at the top have no impact on computed aerosol properties. The same applies to cloud.
![image](https://github.com/JCSDA/CRTMv3/assets/18148322/df89ac40-5878-42f7-9fa5-7377a2773400)



> It shouldn't have any impact if all of the correct variables are specified replacing the background climatology.

Yes to Ben's question. 

Closing this issue now.
