### ISSUE TITLE
verify surface emissivity jacobian in cloudy conditions across spectrum

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#152]
in v2.4.x and 3.x, numerous questions have been raised recently regarding the validity of surface emissivity Jacobian.

(1) different compilers (gfortran, ifort)
(2) persistent /  consistent reference results table to compare against
(3) different cloud tables
(4) across all released and current versions (2.3 - 3.x)

**Comment by quanhualiu** [comment]
For user specified surface emissivity and scattering cases, the surface emissivity jacobian can be corrected by changing one line code:
From
  User_Emissivity_AD = ZERO
to
 User_Emissivity_AD = sum(SfcOptics_AD%Emissivity(1:nZ,1))
