### ISSUE TITLE
Add SHASUM check to Get_CRTM_Binary_Files.sh

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#17]
Presently there's no check against the tarball that gets downloaded from the FTP site.  This issue is to posit potential options for checking the validity of the file prior to uncompressing it.   

Key considerations: needs to be easy to maintain.

**Comment by symoore90** [comment]
Hi @BenjaminTJohnson can you move this issue to the appropriate timeline it looks like there is a current sprint period attached to it.
