### ISSUE TITLE
user manual and python API for CRTM V3 ?

### ISSUE THREAD

**Issue by nuitlejour** [JCSDA/CRTMv3#177]
Dear, sir/ma'am
Is there any online or pdf manual for crtm V3?
Is there a python API for crtm V3 ?
thank you for your time.

**Comment by BenjaminTJohnson** [comment]
@nuitlejour Hello, there's no python API , per se, but here is PyCRTM (github.com/JCSDA/PyCRTM) that has not been adopted to CRTMv3 yet.   PyCRTM is a front-end for CRTM v2.4.    It probably wouldn't be too much trouble to port it to CRTMv3, but unfortunately we don't have the time or funding to work on this right now.   

Regarding the userguide, you can find the latest version attached here:
[CRTM_User_Guide_v3.1.0.pdf](https://github.com/user-attachments/files/16850166/CRTM_User_Guide_v3.1.0.pdf)

**Comment by nuitlejour** [comment]
thank you , I will close this now.
