### ISSUE TITLE
CRTM-CSEM integration 

### ISSUE THREAD

**Issue by mingchen36** [JCSDA/CRTMv3#2]
The Community Surface Emissivity Model (CSEM) evolved from the existing surface modules of the Community Radiative Transfer Model (CRTM), but with completely redesigned model structure to facilitate the implementation of new surface RT models. Multiple model options  may be easily implemented and accommodated in the CSEM framework. In practical applications, CSEM may be used as a standalone surface RT research tool, or used as a sub-system to provide the surface radiative conditions for CRTM, significantly leveraging the development and improvement efforts of CRTM.
CSEM V1.0.0 includes all the existing CRTM surface functionality, and is ready for the integration with CRTM3.0. A new branch will be created to develop the integrated CRTM version.

**Comment by BenjaminTJohnson** [comment]
closing this issue since no work has been performed for several months.
