### ISSUE TITLE
test_k_matrix_AOD

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#28]
With standalone ecbuild and branch `feature/v241_merge_test`, the `test_k_matrix_AOD` tests fail sometime, for example:

```
 ctest -R test_k_matrix_AOD
Test project /Users/dangch/Documents/CRTM/CRTM_dev/crtm_code_review/CRTMv3_test/build
    Start 75: test_k_matrix_AOD_cris-fsr_n21
1/6 Test #75: test_k_matrix_AOD_cris-fsr_n21 ...***Failed   13.29 sec
    Start 76: test_k_matrix_AOD_v.abi_g18
2/6 Test #76: test_k_matrix_AOD_v.abi_g18 ......   Passed    0.08 sec
    Start 77: test_k_matrix_AOD_cris399_npp
3/6 Test #77: test_k_matrix_AOD_cris399_npp ....   Passed    2.48 sec
    Start 78: test_k_matrix_AOD_v.abi_gr
4/6 Test #78: test_k_matrix_AOD_v.abi_gr .......   Passed    0.08 sec
    Start 79: test_k_matrix_AOD_abi_g18
5/6 Test #79: test_k_matrix_AOD_abi_g18 ........   Passed    0.13 sec
    Start 80: test_k_matrix_AOD_airs_aqua
6/6 Test #80: test_k_matrix_AOD_airs_aqua ......***Failed   14.80 sec

67% tests passed, 2 tests failed out of 6

Label Time Summary:
CRTM_Tests    =  30.85 sec*proc (6 tests)
crtm_tests    =  30.85 sec*proc (6 tests)
openmp        =  30.85 sec*proc (6 tests)
script        =  30.85 sec*proc (6 tests)

Total Test time (real) =  33.86 sec

The following tests FAILED:
	 75 - test_k_matrix_AOD_cris-fsr_n21 (Failed)
	 80 - test_k_matrix_AOD_airs_aqua (Failed)
Errors while running CTest
```

I went through all the code updates on aerosols, it is still unclear to me
(1) why some of these tests fail occasionally when the others pass with v3 code.
(2) why the same updates work well with v2.4.1 codes.
I'll spend more time to find out the cause with v3 codes.

**Comment by chengdang** [comment]
@BenjaminTJohnson @StegmannJCSDA @huishao-r 

For question 1:
With the standalone CRTM, I printed the output of AOD related calculation at each steps (CRTM modules), and could not find any segmentation fault.

For each sensors, I then print out the AOD K_matrix results used for the test comparison:
(1) Results from the first time run that saved in a temporary binary file, and then being read again for comparison (atm_k):
https://github.com/JCSDA/CRTMv3/blob/2b5a0c5fa9947f9cab2fb40d8077d5210b38c716/test/mains/regression/k_matrix/test_AOD/test_AOD.f90#L272
(2) Results from the second time run (Atmosphere_K):
https://github.com/JCSDA/CRTMv3/blob/2b5a0c5fa9947f9cab2fb40d8077d5210b38c716/test/mains/regression/k_matrix/test_AOD/test_AOD.f90#L203


For `cris-fsr_n21 ` and `airs_aqua `, `Atmosphere_K` are reasonable, while the results read from the temporary file are all zeros/Nan (`atm_k`). For the other sensors, `Atmosphere_K` and `atm_k` are identical, therefore all these tests passed.

I wonder if this is because `cris-fsr_n21 ` and `airs_aqua` each has more than 2000 channels, while the number of channels are much smaller for the other sensors.

**Comment by chengdang** [comment]
For question 2:

With CRTM V2.4.1, `test_k_matrix_AOD_airs_aqua` usually pass without any issue despite the same number of channels. For this I don't understand. 

With this test, the `Atmosphere_K` computed with CRTM v3 and CRTM v2.4.1 are identical.

**Comment by StegmannJCSDA** [comment]
Thank you @chengdang . The number of channels might be an explanation. I had no luck with the ufo tests yet.

**Comment by BenjaminTJohnson** [comment]
@chengdang @StegmannJCSDA  @huishao-r 

The issue with CRTM v3.0 and AOD / other failures is related to openMP.   I created a `CRTMv3` feature branch: `feature/btj_test_disable_openmp`  where openmp is disabled in the build scripts and in the code (very hackish), and only 2 ufo ctests fail using this branch along with Hui's modified v3 branch in UFO: `feature/btj_v3.0.0_fix_hs`.

The following two tests fail:
```
         80 - ufo_test_tier1_test_ufo_qc_met_office_buddy_check (Failed)
         86 - ufo_test_tier1_test_ufo_qc_ocean_vertical_stability_check (Failed)
```

edited to add: this includes the tier2 tests, but the two crtm AOD tests appear to have been removed in this branch.  I will re-enable and test again.

**Comment by climbfuji** [comment]
This clearly shows that we need a way to disable OpenMP on a per-repo basis as part of our builds. Right now, we can't, it's an all-or-nothing approach with ecbuild.

See https://github.com/NOAA-EMC/spack-stack/issues/519 for a related spack-stack issue. Once we've got the capability/variant added there, we dont have to worry about ecbuild. crtm will have OpenMP enabled or disabled as part of the spack-stack build (we can have both available withe very release).

**Comment by huishao-r** [comment]
@BenjaminTJohnson Did you turn on the ctest I commented out? I had to since it was prepared for the PR.

**Comment by BenjaminTJohnson** [comment]
> @BenjaminTJohnson Did you turn on the ctest I commented out? I had to since it was prepared for the PR.

No, I realized after I made the comment that those tests were not turned on.    Do you have a quick way to re-enable those, or is it manually editing different CMakeLists.txt files?

**Comment by huishao-r** [comment]
Manually. Or check out the version from develop if there is no other difference.

**Comment by chengdang** [comment]
Closing this issue for stand-alone CRTM AOD tests. 
For further updates on UFO based tests, please see the original issue #19
