### ISSUE TITLE
Find a better solution to store and disseminate CRTM coefficients

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/CRTMv3#3]
## Description

We need a better solution to store and disseminate CRTM coefficients. GDEX is free, but inconvenient as it requires the help from UCAR IT people to maintain the data sets. We should explore other options:
- [ ] AWS S3 (provided and paid by AWS)
- [ ] AWS S3 (provided and paid by us)
- [ ] NOAA data lake
- [ ] AWS S3-backed `git-lfs` (provided and paid by either AWS or us)
- [ ] Xenodo, Pangea, etc. - providers that store ESM/NWP data (and possibly also issue DOIs for it)

This issue covers exploring the different options, not implementing it across all JEDI repos.

**Comment by BenjaminTJohnson** [comment]
Regarding Zenodo (https://help.zenodo.org/):

> What are the size limits in Zenodo?

> We currently accept up to 50GB per dataset (you can have multiple datasets); there is no size limit on communities. 
> However, we don't want to turn away larger use cases. If you would like to upload larger files, please [contact us](https://zenodo.org/support), and we will do our best to help you. Please be aware that we cannot offer infinite space for free, so donations towards sustainability are encouraged.  Higher quotas can be requested and granted on a case-by-case basis.

Regarding Rate Limiting:

<html>
<body>
<h1 id="rate-limiting" style="font-size: 36px; margin: 2em 1616.5px 12px 0px; font-family: Roboto, sans-serif; font-weight: 300; padding: 0.5em 28px; box-sizing: border-box; display: block; text-shadow: rgb(255, 255, 255) 0px 1px 0px; clear: both; border-bottom: 1px solid rgb(204, 204, 204); border-top: 1px solid rgb(221, 221, 221); background-image: linear-gradient(rgb(255, 255, 255), rgb(249, 249, 249)); color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Rate Limiting</h1><p style="margin-right: 1616.5px; padding: 0px 28px; box-sizing: border-box; display: block; text-shadow: rgb(255, 255, 255) 0px 1px 0px; line-height: 1.6; margin-top: 0px; color: rgb(51, 51, 51); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For our content and services to be available to everyone we have to make sure that our resources are being distributed fairly. To achieve this, we have rate-limiting measures in place which limit the number of requests users can perform in a time window. Depending on the complexity and load of each request, different endpoints have different limits configured.</p>

Pages | Limitations
-- | --
Global limit for guest users | 60 requests per minute, 2000 requests per hour
Global limit for authenticated users | 100 requests per minute, 5000 requests per hour
OAI-PMH API harvesting | 120 requests per minute
Thumbnails for image records | 20 requests per minute


</body>
</html>

**Comment by StegmannJCSDA** [comment]
I'm also adding a brief list of requirements for the coefficient data access that should be fulfilled under ideal circumstances.
Three different categories of users with different requirements will access the coefficients:

- **CRTM Users**: Need to be able to see which coefficients are available and then select the ones they want to download for their CRTM application (read only access). Splitting the data set into a public and private part would also be desirable.
- **JEDI Developer**: Need to be able to quickly download only the coefficients needed for testing the CRTM as a part of JEDI tests. (please feel free to add requirements here)
- **CRTM Core Team Developers**: Need all of the above and need to be able to quickly and easily add new coefficients and modify existing ones. Since the CRTM coefficients are actually an integral part of the CRTM code, version control for the coefficient files is also highly desirable.

**Comment by climbfuji** [comment]
We have started looking into this, and also talked with our partners at AWS. While they are looking into the Amazon-paid S3 storage option (called open data), we are going to explore the S3-backed git-lfs option.

**Comment by StegmannJCSDA** [comment]
Data version control also looks like an interesting solution, but I haven't looked into it in detail yet:
https://dvc.org/

**Comment by BenjaminTJohnson** [comment]
This topic moves forward to AOP24.  Closing in favor of a JCSDA-wide topic that pertains to all data format storage and dissemination.    For CRTM specifically, we adopted a new versioning scheme (https://github.com/JCSDA/CRTMv3/issues/70).   binary data is disseminated via S4 FTP, GDEX (legacy), and GIT LFS (limited / legacy).
