### ISSUE TITLE
Bug in NESDIS_LandEM_Module.f90 regarding Soil_Moisture_Content

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#30]
Soil_Moisture_Content is specified by input as g/cm^3 (according to the code and CRTM user guide), but gets restricted to [0,1] via the max/min operation below.   I suspect that this was a confusion between a typical fractional expression of soil moisture content (e.g., cm^3/cm^3) and the content (g/cm^3). 

i.e., in `NESDIS_LandEM_Module.f90`:
``` 
 ! By default use the
    ! Assign local variable
    mv               = Soil_Moisture_Content  

...

    ! Check soil moisture content range
    mv = MAX(MIN(mv,ONE),ZERO)
```

Recommended solution for v3:   use a fractional value for inputs, and update the documentation / calling routines accordingly.   Will need to check GSI / UFO as well.    I suspect the impact has been limited since soil moisture contents are frequently less than 1 g/cm^3.

I remain, however, confused about finding soil moisture content values in the literature that are as high as 1.6 g/cm^3, considering that the density of pure water is 1 g/cm^3... seems like it would be impossible to have a value greater than 1.

**Comment by BenjaminTJohnson** [comment]
Additional information in this thread:

https://github.com/JCSDA-internal/ufo/issues/2301

**Comment by StegmannJCSDA** [comment]
> I remain, however, confused about finding soil moisture content values in the literature that are as high as 1.6 g/cm^3, considering that the density of pure water is 1 g/cm^3... seems like it would be impossible to have a value greater than 1.

@BenjaminTJohnson if I understand correctly, fluid flow through porous media like soil isn't necessarily considered incompressible, so the mass density can exceed $1.0$ $\frac{g}{cm^3}$, as long as conservation of (water) mass requires it.

**Comment by chengdang** [comment]
Link comments on this topic https://github.com/JCSDA-internal/fv3-jedi/issues/852#issuecomment-1513464270

**Comment by BenjaminTJohnson** [comment]
@chengdang can you follow up on this issue, and review the relevant details regarding expected ranges of input for soil moisture -- also have a look at the UFO interface, to ensure that the values are being passed into CRTM as expected.

**Comment by chengdang** [comment]
@BenjaminTJohnson Sure, I'll follow up on this.

**Comment by chengdang** [comment]
@BenjaminTJohnson, this issue should be closed for now and move to AOP 2024
