### ISSUE TITLE
tracking failures in check_crtm.F90

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#33]
Noticed that check_crtm.F90 is crashing in v3, when it reaches the point in CRTM_Forward checking if the option Apply_NLTE_Correction is true.   Somewhere in the code, the Opt% structure is being corrupted. 

Also, the profile_solution function is not returning properly, when the function is called, all code after the function are not executed.  Probably related to the above issue.

**Comment by BenjaminTJohnson** [comment]
Removing the openMP directives solves the issue, but we definitely want openMP to work.  This suggests that there's a conflict with the way openMP is implemented in CRTM_Forward.f90 in the v3 code.    Will compare to previous versions to verify the implementation in v3.

**Comment by BenjaminTJohnson** [comment]
@chengdang 
```
               CALL interp_2D( AeroC%pcoeff( asi%i1:asi%i2, fix_rh, asi%j1:asi%j2, fix_sig, k, l+AerosolScatter%lOffset, m), &
                    asi%wlp, asi%xlp, pcoeff(l,m) )
```
This the offending line for AOD, in `CRTM_AerosolScatter.f90`.  All of the indexing values seem reasonable, but trying to output the AeroC%pcoeff using those values causes the failure.  This usually suggests a memory allocation error.  


The trace is:
```
10: Image              PC                Routine            Line        Source
10: test_forward_test  0000000000425A5A  for__signal_handl     Unknown  Unknown
10: libpthread-2.17.s  00007F942F8595D0  Unknown               Unknown  Unknown
10: libcrtm.so         00007F9432BC9211  crtm_aerosolscatt     Unknown  Unknown
10: libcrtm.so         00007F9432BC75E5  crtm_aerosolscatt     Unknown  Unknown
10: libcrtm.so         00007F9432BD2A4D  crtm_aod_module_m     Unknown  Unknown
10: test_forward_test  000000000040E8C4  Unknown               Unknown  Unknown
10: test_forward_test  000000000040DB12  Unknown               Unknown  Unknown
10: libc-2.17.so       00007F942F49F495  __libc_start_main     Unknown  Unknown
10: test_forward_test  000000000040DA29  Unknown               Unknown  Unknown
1/1 Test #10: test_forward_AOD_v.abi_g18 .......***Failed    0.39 sec
```
`aerosolscatter` is called from `aod_module`.

**Comment by BenjaminTJohnson** [comment]
shape of AeroC%pcoeff is: `61 1 36  1  8  38  1`

**Comment by chengdang** [comment]
Checking this now.

**Comment by chengdang** [comment]
Hmm, AeroC%pcoeff should be in 7 dimensions: 61    1     36    1     8     38   1     1

**Comment by BenjaminTJohnson** [comment]
@chengdang I think I found the issue.  The last dimension of pcoeff is size 1, but there's a value of 5 trying to be used in it.

Specifically, m=5, where m is the number of  phase elements....`AerosolScatter%n_Phase_Elements`

**Comment by chengdang** [comment]
> @chengdang I think I found the issue. The last dimension of pcoeff is size 1, but there's a value of 5 trying to be used in it.
> 
> Specifically, m=5, where m is the number of phase elements....`AerosolScatter%n_Phase_Elements`

Okay... I guess this is the set up for polarized calculation?

**Comment by chengdang** [comment]
Checking the following related variables:


1. In the AerosolCoeff table, n_Phase_Elements = 1
2. CRTM_Parameters.f90:  INTEGER, PUBLIC, PARAMETER :: MAX_N_STOKES = 4
3. CRTM_AtmOptics_type: n_Phase_Elements   = 0

**Comment by chengdang** [comment]
The issue could be caused by:

```
      CALL CRTM_AtmOptics_Create( AtmOptics, &
                                  Atmosphere(m)%n_Layers, &
                                  MAX_N_LEGENDRE_TERMS, &
                                  MAX_N_PHASE_ELEMENTS  )
```

Where MAX_N_PHASE_ELEMENTS = 6

Actually, looking into this function I think it shouldn't be the issue.

**Comment by StegmannJCSDA** [comment]
> In the AerosolCoeff table, n_Phase_Elements = 1

As far as I can see the `n_Phase_Elements` has to come from the Aerosol LUT file.

If `pcoef` is supposed to represent phase matrix expansion coefficients here, then the correct value for `n_Phase_Elements` from theory should be 6 for a Stokes vector with 4 elements.

**Comment by BenjaminTJohnson** [comment]
@chengdang perhaps it's during the allocation step that it's not receiving the correct information about n_Phase_Elements?  I won't be able to get back to the code until later -- either way, I think this is a key issue preventing AOD from working properly.

**Comment by BenjaminTJohnson** [comment]
@chengdang I think the issue is related to the fact that the AerosolCoeff file that we provide only has 1 phase element. CRTMv3  wants up to 6 phase elements.   CRTM v2.4.0  has MAX_N_PHASE_ELEMENTS = 1, whereas v3 has it = 6.

I simply changed CRTM_Parameters.f90 MAX_N_PHASE_ELEMENTS to 1 again, and the AOD ctests do not fail after that.  

This suggests that  there needs to be a way to cleanly use LUTs that support between 1 and 6 phase elements, and that the max should only be as high as what's available from the coefficient file.

**Comment by chengdang** [comment]
Working on this today.

**Comment by chengdang** [comment]
Added `AeroC` in ` CRTM_AOD_Module`  and modified `CRTM_AtmOptics_Create` calls with  `AeroC%N_PHASE_ELEMENTS`. This seems solved the issue, under more tests now.
```

 CALL CRTM_AtmOptics_Create( AtmOptics, &
                                  Atmosphere(m)%n_Layers, &
                                  MAX_N_LEGENDRE_TERMS, &
                                  AeroC%N_PHASE_ELEMENTS  )
```

**Comment by chengdang** [comment]
Code update is pushed to branch https://github.com/JCSDA/CRTMv3/tree/hotfix/cd_AOD_nphase

Standalone CRTM AOD tests passed, including `test_forward_AOD_v.abi_g18`. Printed the above mentioned `variable m ` in `CRTM_AerosolScatter.f90` and made sure it was always 1. Note that strangely this test always passes on my MacPro. 

Need to run the ufo AOD tests to test this fix.
