### ISSUE TITLE
Extend quieting to quiet all CRTM output, to reduce logfile sizes

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#50]
This will extend "QUIET" to cover all output messages from CRTM, since CRTM can be called millions of times in operational runs, this options should reduce logfile sizes substantially.

**Comment by BenjaminTJohnson** [comment]
New reference: https://github.com/JCSDA-internal/crtm/issues/442

**Comment by BenjaminTJohnson** [comment]
@chengdang is this something you're willing to tackle?   The way that "quiet" is implemented through CRTM is generally on a subroutine-by-subroutine basis, some subroutines do not have quiet options at all, and depending on how CRTM is called, it fills up log files with lots of unnecessary output, per the above reference.    I like the use of `(Process_ID == Output_Process_ID)` to control output, this could be used to set a `quiet` flag (when those values exist) that gets passed into all subroutines (or sets the `quiet` flags for those that exist already).    This would be for general CRTMv3 develop branch, not applied to any particular release.

**Comment by chengdang** [comment]
I probably won't have time to work on this thoroughly until after AGU, especially on the openmp part.
To remove the coefficient loading information for now, see PR https://github.com/JCSDA/CRTMv3/pull/93

**Comment by chengdang** [comment]
Related issues:
https://github.com/JCSDA/CRTMv3/issues/96
https://github.com/JCSDA-internal/crtm/issues/442

All unnecessary CRTM logs have been removed except for the output of `CRTM_SensorData_IsValid(WARNING)`, to which a solution has been found. See issue #96 

Closing this one for now.
