### ISSUE TITLE
Commented out conditional statement leading to compilation failure

### ISSUE THREAD

**Issue by tom-j-h** [JCSDA/CRTMv3#57]
I attempted to build the JEDI fv3-bundle which points to the develop branch of this repo. Compilation of this repo failed at this section of the code:
https://github.com/JCSDA/CRTMv3/blob/24cc3701cbc1ded6e8df1cc6ad33e6655386290b/src/CRTM_LifeCycle.f90#L665-L691
I have no Fortran knowledge, but syntax highlighting on GitHub and in an editor shows line 675 as a comment. This doesn't look right to me based on the ```END IF```'s. Deleting the backslash on line 674 stops 675 from being a comment, and compilation was then successful (will link PR).

**Comment by tom-j-h** [comment]
I don't have permission to push a branch to remote so no PR.

**Comment by BenjaminTJohnson** [comment]
Hi Tom,

Thanks for the bug report!   I'll fix it on my side, but not until Monday
-- on the road.

Cheers,

Ben

**Comment by tom-j-h** [comment]
Thanks Ben!

**Comment by chengdang** [comment]
@tom-8822 Hello Tom, I just merged a fix into develop repo. Please try it now see if it resolve the issue. Thanks.

**Comment by tom-j-h** [comment]
@chengdang it works now! Thanks for the fix.
