### ISSUE TITLE
SIMOBS-78: CRTM release v3.1.0, new features, code enhancements, coefficients updates, and etc

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#63]
CRTM release v3.1.0, new features, code enhancements, coefficients updates, and etc

**Comment by symoore90** [comment]
Is this for the next release? or the end of the AOP? @chengdang

**Comment by chengdang** [comment]
@symoore90 this is for the next release, so perhaps AOP 2024?

**Comment by symoore90** [comment]
Ok thanks

**Comment by BenjaminTJohnson** [comment]
v3.1.0 is essentially completed now.
