### ISSUE TITLE
Nalli2.IRsnow.EmisCoeff.nc4 needs to be uploaded to crtm_coefficients_3.0.0_skylab_6.0.tar.gz

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#65]
JEDI (spack-stack 1.4.1) ctests 520 failed:

`520 - Unit_test_emis_coeff_io_nc (Failed)`

because `Nalli2.IRsnow.EmisCoeff.nc4` has not been uploaded to`/pub/s4/CRTM/file/crtm_coefficients_3.0.0_skylab_6.0.tar.gz`

This is an optional emissivity coefficient file, that it won't impact any skylab tests.

**Comment by chengdang** [comment]
This file is uploaded to` fix_REL-3.0.0_20230802.tgz`, under folder `fix_REL-3.0.0_20230802/fix/EmisCoeff/IR_Snow/Nalli/netCDF`

**Comment by chengdang** [comment]
@BenjaminTJohnson Can I update `/pub/s4/CRTM/file/crtm_coefficients_3.0.0_skylab_6.0.tar.gz` to include  `Nalli2.IRsnow.EmisCoeff.nc4`? Does this change the md5 checksum value?

This file can also be added later on as it does not impact any JEDI tests

**Comment by BenjaminTJohnson** [comment]
needs to have associated OBS issue to enable use of Nalli2.IRSnow.    

need to change the directory structure of the tarball to skylab_6.0, instead of 4.0.

**Comment by BenjaminTJohnson** [comment]
completed.

`https://bin.ssec.wisc.edu/pub/s4/CRTM/file/crtm_coefficients_3.0.0_skylab_6.0.tar.gz`
md5sum:  `a6103cd2c57b89c5e3a32ce489e623d8`
