### ISSUE TITLE
Preparation for CRTM User/Developer Workshop with Emphasis on CRTM v3

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#86]
## Existing Resources for CRTM Workshop:
1. **Tutorial Cases**:
   - A collection of tutorial cases is available on [GitHub](https://github.com/StegmannJCSDA/CRTM_tutorial) which covers topics like computing instrument weighting functions with CRTM, using the CRTM K-Matrix in other applications, and a bispectral retrieval example for cloud optical thickness and effective radius. These tutorials are designed for CRTM versions REL-2.1.3 to 2.3.0.
   - A set of plotting scripts requiring Python, NumPy, and Matplotlib are provided as part of these tutorial cases.

2. **Community Discussions**:
   - There are forum discussions on [JCSDA's forum](https://forums.jcsda.org) around CRTM tutorial cases and legacy build systems, which could be utilized for interactive Q&A sessions during the workshop.

3. **Previous Workshop Topics**:
   - Past workshops have covered forecast experiments for CRTM releases, bug fixes, and user support. 

## Required Developments for CRTM v3 Workshop:
1. **Updated Tutorial Cases**:
   - Development of new tutorial cases or updating existing ones to be compatible with CRTM v3.
   - Additional scripts or tools for plotting and visualization that highlight the new features and improvements in CRTM v3.

2. **Documentation**:
   - Comprehensive documentation covering the new features, improvements, and any backward incompatible changes in CRTM v3.
   - Instructions for setting up the development environment for CRTM v3 including any new dependencies.

3. **Community Engagement**:
   - A platform for users and developers to discuss, report issues, and propose new features or improvements for CRTM v3.
   - Scheduled Q&A sessions or forums for addressing queries, discussions on best practices, and sharing experiences with CRTM v3.

4. **Code Repositories**:
   - A well-organized code repository with branches for different versions of CRTM, including v3.
   - Clear instructions on how to contribute, report issues, and propose new features or improvements.

5. **Workshop Infrastructure**:
   - Setting up necessary infrastructure for hosting the workshop either virtually or in-person.
   - Ensuring the availability of resources like presentation materials, code repositories, and discussion forums for a smooth workshop experience.

This issue aims to kickstart the preparation for the CRTM User/Developer Workshop with a spotlight on transitioning to CRTM v3. Contributions from the community in terms of updated tutorial cases, documentation, and engagement platforms are highly encouraged to make this workshop productive and informative.

**Comment by BenjaminRuston** [comment]
@BenjaminTJohnson should we involve Kristen and Kammie in this they could help out potentially

**Comment by BenjaminTJohnson** [comment]
Closing: user/developer workshop cancelled for AOP23 and AOP24.
