### ISSUE TITLE
Can we reduce the verbosity of the CRTM linking steps?

### ISSUE THREAD

**Issue by fmahebert** [JCSDA/CRTMv3#87]
When building CRTM within the jedi bundle, I see a lot of output from the CRTM link targets. It looks like each linker invocation is being echoed to terminal. No doubt this is very useful in debugging the CRTM build system, but is it necessary for most users? For myself, I'd prefer a lower verbosity by default so that CRTM's build output is a better match to the other repos and to keep the build logs are easier to look at...

I'd be curious to know how the CRTM team would feel about reducing the default verbosity of linking CRTM.

To illustrate, below, I'm pasting a snippet from a recent build showing the output from just three link targets, showing that it's a bit overwhelming to have a terminal full of this. (Pardon the terrible formatting: a Github code block doesn't wrap lines, so this not-a-code-block rendering is more useful to illustrate the problem...)

<code>
[ 44%] Building Fortran object crtm/test/CMakeFiles/test_check_crtm.dir/mains/application/check_crtm.F90.o
[ 44%] Linking Fortran executable test_check_crtm
/usr/local/bin/gfortran-12 -fopenmp -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/libevent-2.1.12-3oxgj5o/lib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/pmix-4.2.3-ax37hxn/lib -Wl,-commons,use_dylibs -Wl,-commons,use_dylibs -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/libevent-2.1.12-3oxgj5o/lib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/pmix-4.2.3-ax37hxn/lib  -D_REAL8_ -ffree-line-length-none -O0 -g -fcheck=bounds -fbacktrace -finit-real=snan -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.7 CMakeFiles/test_check_crtm.dir/mains/application/check_crtm.F90.o -o test_check_crtm  -Wl,-rpath,/Users/hebert/work/jedi/build/lib ../../lib/libcrtm.dylib /usr/local/Cellar/gcc@12/12.3.0/lib/gcc/12/libgomp.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-fortran-4.6.0-vhtxnfa/lib/libnetcdff.dylib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-fortran-4.6.0-vhtxnfa/lib -lnetcdff -lnetcdf -lnetcdf -lm /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-c-4.9.2-d4wix4s/lib/libnetcdf.dylib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-c-4.9.2-d4wix4s/lib -lnetcdf /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_usempif08.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_usempi_ignore_tkr.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_mpifh.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi.dylib
[ 44%] Built target test_check_crtm
[ 44%] Building Fortran object crtm/test/CMakeFiles/test_check_crtm_random.dir/mains/application/check_crtm_random_profiles.F90.o
[ 44%] Linking Fortran executable test_check_crtm_random
/usr/local/bin/gfortran-12 -fopenmp -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/libevent-2.1.12-3oxgj5o/lib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/pmix-4.2.3-ax37hxn/lib -Wl,-commons,use_dylibs -Wl,-commons,use_dylibs -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/libevent-2.1.12-3oxgj5o/lib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/pmix-4.2.3-ax37hxn/lib  -D_REAL8_ -ffree-line-length-none -O0 -g -fcheck=bounds -fbacktrace -finit-real=snan -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.7 CMakeFiles/test_check_crtm_random.dir/mains/application/check_crtm_random_profiles.F90.o -o test_check_crtm_random  -Wl,-rpath,/Users/hebert/work/jedi/build/lib ../../lib/libcrtm.dylib /usr/local/Cellar/gcc@12/12.3.0/lib/gcc/12/libgomp.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-fortran-4.6.0-vhtxnfa/lib/libnetcdff.dylib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-fortran-4.6.0-vhtxnfa/lib -lnetcdff -lnetcdf -lnetcdf -lm /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-c-4.9.2-d4wix4s/lib/libnetcdf.dylib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-c-4.9.2-d4wix4s/lib -lnetcdf /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_usempif08.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_usempi_ignore_tkr.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_mpifh.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi.dylib
[ 44%] Built target test_check_crtm_random
[ 44%] Building Fortran object crtm/test/CMakeFiles/TL_TEST.dir/mains/unit/Unit_Test/test_TL.f90.o
[ 44%] Linking Fortran executable TL_TEST
/usr/local/bin/gfortran-12 -fopenmp -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/libevent-2.1.12-3oxgj5o/lib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/pmix-4.2.3-ax37hxn/lib -Wl,-commons,use_dylibs -Wl,-commons,use_dylibs -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/libevent-2.1.12-3oxgj5o/lib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/pmix-4.2.3-ax37hxn/lib  -D_REAL8_ -ffree-line-length-none -O0 -g -fcheck=bounds -fbacktrace -finit-real=snan -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.7 CMakeFiles/TL_TEST.dir/mains/unit/Unit_Test/test_TL.f90.o -o TL_TEST  -Wl,-rpath,/Users/hebert/work/jedi/build/lib ../../lib/libcrtm.dylib /usr/local/Cellar/gcc@12/12.3.0/lib/gcc/12/libgomp.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-fortran-4.6.0-vhtxnfa/lib/libnetcdff.dylib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-fortran-4.6.0-vhtxnfa/lib -lnetcdff -lnetcdf -lnetcdf -lm /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-c-4.9.2-d4wix4s/lib/libnetcdf.dylib -L/Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/netcdf-c-4.9.2-d4wix4s/lib -lnetcdf /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_usempif08.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_usempi_ignore_tkr.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi_mpifh.dylib /Users/hebert/work/spack-stack-1.5.0/envs/skylab-v6/install/apple-clang/14.0.0/openmpi-4.1.5-2vbokxw/lib/libmpi.dylib
[ 44%] Built target TL_TEST
</code>

**Comment by BenjaminTJohnson** [comment]
It doesn't do that for me, so I wonder if you have an environment variable or alias set somewhere to increase verbosity?

Ah, I see it's macos, maybe that's the difference?  I can't get spack stack 1.5 to work yet on my mac (intel).

edit:I was wrong, I'm getting the linker messages verbosely, even when using `make -s`

**Comment by BenjaminTJohnson** [comment]
@fmahebert I'm open to recommendations here for quieting the linker output.

**Comment by fmahebert** [comment]
@BenjaminTJohnson Okay, glad to see you get this output too, I just verified I see it on several different platforms... I don't know how to quiet the linker off the top of my head, but I'll investigate (not urgently). The other JEDI repos don't have this output, so perhaps by looking somewhere in there or in ecbuild I can find some trick...

**Comment by fmahebert** [comment]
I think the culprit may be line 18 in `tests/CMakeLists.txt`
```
set(CMAKE_VERBOSE_MAKEFILE ON)
```

When I delete this line and rebuild, I (unsurprisingly!) no longer get verbose output. Do you think this could be set to `OFF` by default?

**Comment by BenjaminTJohnson** [comment]
Hmm, i must be losing my mind because this was the first thing I looked for... 
and didn't see it.  I even added the line and set it to off in my local copy...

**Comment by fmahebert** [comment]
@BenjaminTJohnson If you approve, I can put in a CRTM PR to remove this line from the test/CMakeLists? Or would you prefer I keep the line and set it to `OFF`?

**Comment by BenjaminTJohnson** [comment]
@fmahebert sure, go ahead.    I got tied up with other tasks, and forgot to circle back around to this.
