### ISSUE TITLE
Questions about TL/K_Matrix module

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#89]
I have some questions about TL/K-Matrix modules, in particular regarding the placement of the following code block:

```
            ! Combine cloudy and clear radiances for fractional cloud coverage
            IF ( CRTM_Atmosphere_IsFractional(cloud_coverage_flag) ) THEN
              IF( RTV%n_Stokes == 1 ) THEN
              r_cloudy(1) = RTSolution(ln,m)%Radiance  ! Save the 100% cloudy radiance
              RTSolution(ln,m)%Radiance = &
                  ((ONE - CloudCover%Total_Cloud_Cover) * RTSolution_Clear%Radiance) + &
                  (CloudCover%Total_Cloud_Cover * RTSolution(ln,m)%Radiance)
              RTSolution(ln,m)%Stokes(1) = RTSolution(ln,m)%Radiance
              ELSE
              DO ks = 1, RTV%n_Stokes
              r_cloudy(ks) = RTSolution(ln,m)%Stokes(ks)  ! Save the 100% cloudy radiance
              RTSolution(ln,m)%Stokes(ks) = &
                  ((ONE - CloudCover%Total_Cloud_Cover) * RTSolution_Clear%Stokes(ks)) + &
                  (CloudCover%Total_Cloud_Cover * RTSolution(ln,m)%Stokes(ks))              
              END DO
              RTSolution(ln,m)%Radiance = RTSolution(ln,m)%Stokes(1)
              END IF
              ! ...Save the cloud cover in the output structure
              RTSolution(ln,m)%Total_Cloud_Cover = CloudCover%Total_Cloud_Cover
            END IF
```

**Comment by chengdang** [comment]
In forward module, this code block is implemented after calling `CRTM_Compute_RTSolution` twice to compute the `RTSolution` and `RTSolution_Clear` for both overcast and clear sky, respectively.  
https://github.com/JCSDA/CRTMv3/blob/ca1e3387a90fcc2fdb5f619f427f3d5fc02a6121/src/CRTM_Forward_Module.f90#L1024
https://github.com/JCSDA/CRTMv3/blob/ca1e3387a90fcc2fdb5f619f427f3d5fc02a6121/src/CRTM_Forward_Module.f90#L1057

This code block then combines the radiance based on cloud fractions to generate radiance of fractional cloudy sky:
https://github.com/JCSDA/CRTMv3/blob/ca1e3387a90fcc2fdb5f619f427f3d5fc02a6121/src/CRTM_Forward_Module.f90#L1078

**Comment by chengdang** [comment]
In TL and K_Matrix modules, this code block is implemented before calling `CRTM_Compute_RTSolution`, `CRTM_Compute_RTSolution_TL`, `CRTM_Compute_RTSolution_AD`, yet in some of these modules, `RTSolution` and `RTSolution_Clear` are being re-computed. So I'm trying to understand why these are implemented such way.

For example, in `CRTM_Adjoint_Module.f90`, twice before calling `CRTM_Compute_RTSolution` and `CRTM_Compute_RTSolution_TL`
https://github.com/JCSDA/CRTMv3/blob/ca1e3387a90fcc2fdb5f619f427f3d5fc02a6121/src/CRTM_Adjoint_Module.f90#L1035
https://github.com/JCSDA/CRTMv3/blob/ca1e3387a90fcc2fdb5f619f427f3d5fc02a6121/src/CRTM_Adjoint_Module.f90#L1112

In `CRTM_K_Matrix_Module.f90`, multiple times before and after calling `CRTM_Compute_RTSolution_AD`
https://github.com/JCSDA/CRTMv3/blob/ca1e3387a90fcc2fdb5f619f427f3d5fc02a6121/src/CRTM_K_Matrix_Module.f90#L1212
https://github.com/JCSDA/CRTMv3/blob/ca1e3387a90fcc2fdb5f619f427f3d5fc02a6121/src/CRTM_K_Matrix_Module.f90#L1280
https://github.com/JCSDA/CRTMv3/blob/ca1e3387a90fcc2fdb5f619f427f3d5fc02a6121/src/CRTM_K_Matrix_Module.f90#L1327

**Comment by quanhualiu** [comment]
In CRTM_Forward_Module, 
line   1024            Error_Status = CRTM_Compute_RTSolution( &
is always used. It can be using 100% cloud even the actual cloud coverage is < 100% or can be for a clear-sky case.
line 1057      Error_Status = CRTM_Compute_RTSolution( & is used for a partially cloud cover case.
Combine the result RTSolution from line 1024 and RTSolution_Clear from line 1057, one can calculate the result for the partially cloud cases.

**Comment by chengdang** [comment]
Had a meeting and this issue is resolved.
