### ISSUE TITLE
SIMOBS-79: Generic interface for CRTM simulations

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#91]
Develop a generic interface to drive CRTM simulations

**Comment by symoore90** [comment]
Is this epic for Q3? @BenjaminTJohnson @chengdang

**Comment by chengdang** [comment]
@symoore90 it is for Oct - Dec 2023. Thanks.

**Comment by BenjaminRuston** [comment]
per conversation in v8 planning meeting we are closing this now, will open a new epic next AOP if there is a specific requirement for this
