### ISSUE TITLE
Log is too noisy for emerging sensors

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA/CRTMv3#96]
If one runs SkyLab with the full suite of observations, CRTM adds 176,236 lines of warning messages like below:

```
 CRTM_SensorData_IsValid(WARNING) : Invalid WMO Sensor Id Continuing...
 CRTM_SensorData_IsValid(WARNING) : Invalid WMO Satellite Id found. Continuing...
```

This adds 13Mb of warning messages in the log. It would be nice to clean this up (either by fixing the coefficient that causes this warning or by reducing the number of messages).

**Comment by fabiolrdiniz** [comment]
@BenjaminTJohnson, please, fill up the right column as you think it's best.

**Comment by BenjaminTJohnson** [comment]
@fabiolrdiniz Is there any idea which sensor_id is causing this?

**Comment by chengdang** [comment]
Just to circle back to this issue, the WMO IDs of some sensors are set as invalid by CRTM, for example:
https://github.com/JCSDA/CRTMv3/blob/90d52eec1f97bb5a098c9834c4499a17de4ff35b/src/SensorInfo/CRTM_SensorInfo.f90#L57

Assuming instrument coefficients use the same WMO IDs, warnings messages for instrument such as ABI are given by function `CRTM_SensorData_IsValid`
https://github.com/JCSDA/CRTMv3/blob/90d52eec1f97bb5a098c9834c4499a17de4ff35b/src/Surface/SensorData/CRTM_SensorData_Define.f90#L327

Consider comment out the following warnings (if they are not used anywhere):
```
    IF ( SensorData%WMO_Satellite_Id == INVALID_WMO_SATELLITE_ID ) THEN
      msg = 'Invalid WMO Satellite Id found. Continuing...'
      CALL Display_Message( ROUTINE_NAME, msg, WARNING )
    ENDIF
    IF ( SensorData%WMO_Sensor_Id == INVALID_WMO_SENSOR_ID ) THEN
      msg = 'Invalid WMO Sensor Id Continuing...'
      CALL Display_Message( ROUTINE_NAME, msg, WARNING )
    ENDIF
```
This function is called by function `CRTM_Surface_IsValid` in forward, adjoint, TL, K-matrix modules, therefore tons of warning messages.

**Comment by fabiolrdiniz** [comment]
Thanks for your patience, @BenjaminTJohnson. Only now I saw your message above.

> @fabiolrdiniz Is there any idea which sensor_id is causing this?

It might be COWVR (cowvr_ors6) or Tempest (tempest-D_cubesat).
